IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ServiceDeskTicket')
BEGIN
	CREATE TABLE dbo.ServiceDeskTicket (
		IdPrefix INT,
		IdTicket INT IDENTITY(1,1) NOT NULL,
		TicketName VARCHAR(100) NOT NULL,
		Creator INT NOT NULL,
		Assigner INT,
		Assignee INT NULL,
		Coordinate VARCHAR(200),
		IdMunicipality INT NOT NULL,
		IdState INT NOT NULL,
		IdRegion INT NOT NULL,
		Address VARCHAR(200) NOT NULL,
		IdIncidentType INT NOT NULL,
		IdPrimaryCause INT NOT NULL,
		FaultDetail VARCHAR(MAX),
		IdAffectedElement INT NOT NULL,
		IdTicketState INT NOT NULL,
		IdPriorityLevel INT NOT NULL,
		IdSolutionType INT NULL,
		IsTechnicalVisitRequired SiNo NULL,
		IsBrigadeDeployed SiNo NULL,
		IsChangeNetworkTopology SiNo NULL,
		WorkDone VARCHAR(1000) NULL,
		IdConfirmedArea INT NULL,
		IncidentClosureSummary VARCHAR(2000),
		Finisher INT NULL,
		CONSTRAINT PK_ServiceDeskTicket PRIMARY KEY(IdPrefix, IdTicket),
		CONSTRAINT Fk_Prefix FOREIGN KEY(IdPrefix) REFERENCES Prefix(IdPrefix),
		CONSTRAINT Fk_EngineerCreator FOREIGN KEY(Creator) REFERENCES Engineer(EngineerId),
		CONSTRAINT Fk_EngineerAssigner FOREIGN KEY(Assigner) REFERENCES Engineer(EngineerId),
		CONSTRAINT Fk_EngineerAssignee FOREIGN KEY(Assignee) REFERENCES Engineer(EngineerId),
		CONSTRAINT Fk_EngineerFinisher FOREIGN KEY(Finisher) REFERENCES Engineer(EngineerId),
		CONSTRAINT FK_IncidentType FOREIGN KEY(IdIncidentType) REFERENCES IncidentType(IdIncidentType),
		CONSTRAINT FK_PrimaryCause FOREIGN KEY(IdPrimaryCause) REFERENCES PrimaryCause(IdPrimaryCause),
		CONSTRAINT FK_AffectedElement FOREIGN KEY(IdAffectedElement) REFERENCES AffectedElement(IdAffectedElement),
		CONSTRAINT FK_StateServiceDeskTicket FOREIGN KEY(IdState) REFERENCES State(IdState),
		CONSTRAINT FK_RegionServiceDeskTicket FOREIGN KEY(IdRegion) REFERENCES Region(IdRegion),
		CONSTRAINT FK_MunicipalityServiceDeskTicket FOREIGN KEY(IdMunicipality) REFERENCES Municipality(IdMunicipality),
		CONSTRAINT FK_TicketState FOREIGN KEY(IdTicketState) REFERENCES TicketState(IdTicketState),
		CONSTRAINT FK_PriorityLevel FOREIGN KEY(IdPriorityLevel) REFERENCES PriorityLevel(IdPriorityLevel),
		CONSTRAINT FK_SolutionType FOREIGN KEY(IdSolutionType) REFERENCES SolutionType(IdSolutionType),
		CONSTRAINT FK_ConfirmedArea FOREIGN KEY(IdConfirmedArea) REFERENCES ConfirmedArea(IdConfirmedArea)
	)
END