IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SolutionType')
BEGIN
	CREATE TABLE dbo.SolutionType (
		IdSolutionType INT IDENTITY(1,1) NOT NULL,
		Description VARCHAR(100) NOT NULL,
		CONSTRAINT PK_SolutionType PRIMARY KEY (IdSolutionType)
	)
END